dist: bionic	
sudo: false	

language: python	
python:	
  - "3.7"	

notifications:	
  email: false	

env:	
  - TEST_PLATFORM="megaatmega2560"	

before_install:	
  #	
  # Fetch the tag information for the current branch	
  - git fetch origin --tags	
  #	
  # Publish the buildroot script folder	
  - chmod +x ${TRAVIS_BUILD_DIR}/buildroot/bin/*	
  - chmod +x ${TRAVIS_BUILD_DIR}/buildroot/share/tests/*	
  - export PATH=${TRAVIS_BUILD_DIR}/buildroot/bin/:${TRAVIS_BUILD_DIR}/buildroot/share/tests/:${PATH}	

install:	
  #- pip install -U platformio	
  - pip install -U https://github.com/platformio/platformio-core/archive/master.zip	

before_script:	
  # Update PlatformIO packages	
  - platformio update	
  #	
  # Change current working directory to the build dir	
  - cd ${TRAVIS_BUILD_DIR}	
  #	
  # Generate custom version include	
  - generate_version ${TRAVIS_BUILD_DIR}/Marlin/	
  - cat ${TRAVIS_BUILD_DIR}/Marlin/Version.h	
  #	
  - run_tests ${TRAVIS_BUILD_DIR} ${TEST_PLATFORM}

script:	
  - mkdir _builds
  - pio run
  - cp .pio/build/megaatmega2560/firmware.hex _builds/some-build.hex

deploy:
  provider: releases
  token: $GH_TOKEN
  overwrite: true
  file_glob: true
  file: $TRAVIS_BUILD_DIR/_builds/*.hex
  skip_cleanup: true
  on:
    all_branches: true